---
- name: Install Ansible dependencies
  yum: name={{ item }}
  with_items: 
    - autoconf
    - gcc
    - python26-devel 
    - git
  sudo: yes


- name: Install pip
  easy_install: name=pip
  sudo: yes


- name: Install boto
  pip: name=boto  
  sudo: yes


- name: Install botocore
  pip: name=botocore  
  sudo: yes


- name: Install Ansible
  pip: name=ansible  version=latest
  sudo: yes


- name: Ensure ansible log directory exits, ~/logger
  file: path=~/logger  state=directory  


- name: SSH config
  template: src=ssh_config.j2  dest=~/.ssh/config  mode=0600


- name: Ensure /etc/ansible/ exists
  file: path=/etc/ansible/ state=directory  owner=root  group=root  mode=0755  
  sudo: yes


- name: Default hosts config
  template: src=hosts.j2  dest=/etc/ansible/hosts  owner=root  group=root  mode=0644  
  sudo: yes


- name: Copy rsa key from this host
  copy: src=~/.ssh/managed_rsa  dest=~/.ssh/managed_rsa  mode=0400


- name: Copy boto auth config 
  copy: src=~/.boto  dest=~/.boto  mode=0400


- name: bashrc with some pretty aliases
  template: src=.bashrc.j2  dest=~/.bashrc


- name: gitconfig with some pretty aliases
  template: src=.gitconfig.j2  dest=~/.gitconfig

