---
- name: Common role for Amazon linux
  gather_facts: False
  hosts: all
  user: ec2-user
  roles: 
    - { role: auth, when: ec2_tag_role != 'vpn' }
    - { role: common, when: ec2_tag_role != 'vpn' }



- name: Common role for VPN (Ubuntu)
  gather_facts: False
  hosts: all
  user: openvpnas
  roles: 
    - { role: auth, when: ec2_tag_role == 'vpn' }
    - { role: ubuntu_common, when: ec2_tag_role == 'vpn' }
