---
- name: do /etc/sysctl.conf
  template: src=sysctl.conf.j2  dest=/etc/sysctl.conf
  sudo: yes
  notify: sysctl


- name: do /etc/security/limits.conf
  template: src=limits.conf.j2  dest=/etc/security/limits.conf
  sudo: yes
  notify: restart cassandra


- name: do /etc/security/limits.d/90-nproc.conf
  template: src=90-nproc.conf.j2   dest=/etc/security/limits.d/90-nproc.conf
  sudo: yes
  notify: restart cassandra


- name: Ensure OpenJDK is uninstalled
  yum:  name="java-*-openjdk"  state=absent
  sudo: yes


- name: Ensure Oralce JDK is installed
  yum:  name=https://s3-eu-west-1.amazonaws.com/producthealth/repo/jdk-7u60-linux-x64.rpm  state=installed
  sudo: yes


- name: Download and extract Cassandra archive
  shell: curl -s -o cassandra.tgz {{ cassandra_url }} && tar -xf cassandra.tgz && rm cassandra.tgz && mv apache-cassandra* cassandra creates=~/cassandra


- name: Download jna.jar
  shell: curl -s -o ~/cassandra/lib/jna.jar {{ jna_url }}  creates=~/cassandra/lib/jna.jar


- name: Sort out cassandra.yaml template
  template: src=cassandra.yaml_template.j2  dest=~/cassandra/conf/cassandra.yaml_template


- name: Make sure there is a cassandra dir on SSD
  file: name=/ssd/cassandra  state=directory  owner=ec2-user  group=ec2-user


- name: Make sure there is a cassandra dir on EBS
  file: name=/ebs/cassandra  state=directory  owner=ec2-user  group=ec2-user


- name: Make sure /var/log/cassandra exists with correct permissions
  file: name=/var/log/cassandra  state=directory  owner=ec2-user  group=ec2-user
  sudo: yes


- name: Enable application on boot
  service: name=cassandra  enabled=yes  state=started  arguments="{{ cassandra_args }}"
  sudo: yes


- name: Add cassandra bin dir to the PATH
  template: src=cassandra-bin.sh.j2  dest=/etc/profile.d/cassandra-bin.sh
  sudo: yes
